name: Full Stack Build

on:
  push:
    branches: [ "main", "training-server" ]
  pull_request:
    branches: [ "main", "training-server" ]

jobs:
  build-auth-server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js for Auth Server
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies for Auth Server
      run: npm i
      working-directory: ./auth-server

    - name: Build Auth Server
      run: npm run build --if-present
      working-directory: ./auth-server

  build-training-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
  
      - name: Set up Node.js for Training Server
        uses: actions/setup-node@v2
        with:
          node-version: '20'
  
      - name: Install dependencies for Training Server
        run: npm i
        working-directory: ./training-server
  
      - name : Run tests for Training Server
        run: npm test
        working-directory: ./training-server
  
      - name: Build Training Server
        run: npm run build --if-present
        working-directory: ./training-server

  build-upload-server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js for Upload Server
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies for Upload Server
      run: npm i
      working-directory: ./upload-server

    - name: Build Upload Server
      run: npm run build --if-present
      working-directory: ./upload-server
